# Generated by Django 6.0 on 2026-01-16 13:54

import django.core.validators
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the employee', primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('name', models.CharField(help_text='Employee full name', max_length=255, validators=[employees.models.validate_not_empty], verbose_name='Full Name')),
                ('email', models.EmailField(error_messages={'unique': 'An employee with this email already exists.'}, help_text='Employee email address (must be unique)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Email Address')),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Operations', 'Operations')], help_text='Employee department (e.g., HR, Engineering, Sales)', max_length=100, null=True, verbose_name='Department')),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst'), ('Designer', 'Designer'), ('Lead', 'Team Lead'), ('Intern', 'Intern')], help_text='Employee role (e.g., Manager, Developer, Analyst)', max_length=100, null=True, verbose_name='Role')),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when employee record was created', verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'ordering': ['-date_joined', 'name'],
                'indexes': [models.Index(fields=['email'], name='idx_employee_email'), models.Index(fields=['department'], name='idx_employee_dept'), models.Index(fields=['role'], name='idx_employee_role'), models.Index(fields=['-date_joined'], name='idx_employee_date')],
            },
        ),
    ]
